# HTML Identifiers
RACE_TABLE_IDENTIFIER = 'Race Name'
NASCAR_IDENTIFIER = 'NASCAR'
PLAYERS_TABLE_IDENTIFIER = 'Sponsor / Owner'
LOOP_DATA_IDENTIFIER = 'Loop Data Stats'
PRACTICE_DATA_IDENTIFIER = 'Practice'
QUALIFYING_LINK_RESULTS_IDENTIFIER = 'Qualifying Results'
QUALIFYING_RESULTS_TABLE_IDENTIFIER = 'Qualifying results for this race'
LOOP_DATA_TABLE_IDENTIFIER = 'Loop data for this race'
PRACTICE_DATA_TABLE_IDENTIFIER = 'Practice 1 results for this race'
LAPS_IDENTIFIER = 'miles)'
TRACK_LINK_IDENTIFIER = '/tracks'


# CSV Headers
QUALIFYING_RANK = 'Qualifying Rank'
QUALIFYING_TIME = 'Qualifying Time'
QUALIFYING_SPEED = 'Qualifying Speed'
PASS_DIFF = 'Pass Differential'
QUALITY_PASSES = 'Quality Passes'
DRIVER_RATING = 'Driver Rating'
FASTEST_LAPS = 'Fastest Laps'
PRACTICE_RANK = 'Practice Rank'
PRACTICE_TIME = 'Practice Time'
PRACTICE_SPEED = 'Practice Speed'
RACE = 'Race'
DATE = 'Date'
TRACK_NAME = 'Track Name'
LAPS = 'Laps'
TRACK_LENGTH = 'Track Length'
FINISHING_POSITION = 'Finishing Position'
STARTING_POSITION = 'Starting Position'
DRIVER = 'Driver'
CAR_BRAND = 'Car Brand'
LAPS_LED = 'Laps Led'
FANTASY_POINTS = 'Fantasy Points'
QUALIFYING_PRACTICE_RANK = 'Qualifying/Practice Rank'
AVERAGE_FANTASY_POINTS = 'Average Fantasy Points'
AVERAGE_FANTASY_POINTS_FOR_TRACK = 'Average Fantasy Points for Track'

# Other constants
BASE_RACING_REFERENCE_URL = 'https://www.racing-reference.info'
BASE_RACES_URL = BASE_RACING_REFERENCE_URL + '/allraces'
RACE_CSV = 'racing_reference.csv'
TRACK_DESCRIPTION_REGEX = r'\d{0,3} laps.*?miles'
TABLE_ROW_FILTER = {'class': ['odd', 'even']}
